name: rust_tutorial_check

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}', github.run_id, github.run_attempt) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

env:
  TOOLCHAIN_VERSION: 0.1.14

jobs:
  test-zkllvm-rust-workflow:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install zkLLVM DEB package
        run: |
          sudo bash -c "echo 'deb [trusted=yes]  http://deb.nil.foundation/ubuntu/ all main' >>/etc/apt/sources.list"
          sudo apt update
          sudo apt install -y zkllvm=$TOOLCHAIN_VERSION libboost-all-dev

      - name: Install Rust zkLLVM toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -O https://cdn.jsdelivr.net/gh/NilFoundation/zkllvm@master/rslang-installer.py
          python3.7 rslang-installer.py --channel nightly --verbose v$TOOLCHAIN_VERSION
